{% set version = "0.7.3" %}

package:
  name: cython-blis
  version: {{ version }}

source:
  url: https://github.com/adrianeboyd/cython-blis/archive/127e5aaec15382466ae5e8ff16e664ac0f6f4d99.zip
  sha256: 34f1252ee77be4d4fd7c63e6d2130ade598e27c9044b74d68dec23475270308b

build:
  number: 1
  skip: true  # [win and py27]

requirements:
  build:
    - {{ compiler('c') }}
    - clangdev  # [win]
  host:
    - python
    - pip
    - cython
    - setuptools
    - numpy
    - wheel
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pytest
    - hypothesis
  imports:
    - blis
    - blis.py
    - blis.cy
  commands:
    - python -m pytest --tb=native --pyargs blis

about:
  home: http://github.com/explosion/cython-blis
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - blis/LICENSE
  summary: Fast matrix-multiplication as a self-contained Python library – no system dependencies!

  doc_url: https://github.com/explosion/cython-blis
  dev_url: https://github.com/explosion/cython-blis

extra:
  recipe-maintainers:
    - honnibal
    - ines
    - adrianeboyd
